### PR TITLE
Api provides an event index

### PR DESCRIPTION
**Pull request by hmvitous**
# [PT Story](https://www.pivotaltracker.com/story/show/172273855)
```
As an API,
In order to save events that have been created
I need to be able to index the created events
```
## Changes proposed in this pull request:
* Creates index action  for storing events
* Tests happy/sad path
* Generates event model and eventsController
## What I have learned working on this feature:
* Generating models and controllers
* Debugging

### CODE REVIEW

**Comment by hmvitous** [comment]
I looked through it again and fixed minor formatting problems.

**Review by ghost — COMMENTED** [review]
double checked the code with hunter. did not find any issues

**Review by dernathul — APPROVED** [review]
it looks fantastic

**Comment by ghost** [comment]
looks good, but can we please remove the WIP tag, thanks

**Pull request merged**
